#package section in order to be compatible with YPInfrastructure
#see config.yml from ypinfrastructure for details about package section
package:
  type: application
  name: '{{application_name}}'
  version: 0.0.1
  author: 'Name of the author'
  description: 'Text of description'
  dependencies:
    framework:
      ypf: '>={{ypf_version}}'
    plugins:
      captcha: '0.0.1'
    lib:

#Custom paths. YPFramework defines the following paths when sarting, which you can
#use to build your own custom paths:
#  app -> application base path.
#  ypf -> ypframework path
#  www -> public www files path. Generally APP_PATH/www
#  log -> log files path         Generally APP_PATH/support/log
#  tmp -> temporary files path.  Generally APP_PATH/support/tmp
#         below this path you can find compiled templates and caches
paths:
  db: '{%paths.app}/support/db'

#YPFramework can run different configurations for one application. This is
#called an environment. You can use any name that you want except for one rule.
#YPFramework will assume that any environment whose name is not "production" is
#a development environment applying some default settings. On the other hand, it
#will consider the environment "production" as the one meant to be on production systems.
#environments is mandatory

#You can force YPFramework to start working in a specified environment
#mode: 'production'

environments:
  $include: 'support/config/environments/development.yml'
  $include: 'support/config/environments/production.yml'
