package:
  type: plugin
  name: '{{plugin_name}}'
  version: 0.0.1
  author: 'Name of the author'
  description: 'Text of description'
  dependencies:
    framework:
      ypf: '>={{ypf_version}}'
    plugins:
     plugin_name: 'plugin version'
    lib:

paths:
  db: '{%paths.app}/support/db'

#To force execution mode uncomment this line and change it to the correct value
#mode: development

plugins:
  development:

  production:
    #sesion_db:
    #  version: '1.0' # >1.0 รณ >= 1.0
      #path:
      #git:
    #captcha: '1.0'

application:
  development:
    title: '{{application_human_name}}'
    url: 'http://localhost/{{application_name}}'
    root: '/home'
    pack_media: true
    pretty_url: true
    profile: true

  production:
    title: '{{application_human_name}}'
    url: 'http://{{application_name}}.com'
    root: '/home'
    pack_media: false
    pretty_url: true
    profile: true

    minify_output: true

routes:
  home:
    match: '/home(.:format)'
    controller: 'home'
    action: 'index'
    method: 'get'

#  noaction:
#    match: '/:controller(.:format)'
#    action: 'index'

#  default:
#    match: '/(:controller(/:action(/:id)))(.:format)'

databases:
  #One database configuration for each application mode
  development:
    type: SQLite2
    name: '{%paths.db}/development.db'

  production:
    type: SQLite2
    name: '{%paths.db}/production.db'

